//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NajamAutaEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezervacije
    {
        public int RezervacijaID { get; set; }
        public int Klijent { get; set; }
        public int Lokacija { get; set; }
        public int Vozilo { get; set; }
        public Nullable<int> Prikolica { get; set; }
        public System.DateTime PocetakPosudbe { get; set; }
        public System.DateTime IstekPosudbe { get; set; }
        public decimal CijenaPosudbe { get; set; }
    
        public virtual Klijenti Klijenti { get; set; }
        public virtual Lokacije Lokacije { get; set; }
        public virtual Prikolice Prikolice { get; set; }
        public virtual Vozila Vozila { get; set; }

        public decimal IzracunajCijenu()
        {
            decimal brojDana = Convert.ToDecimal((IstekPosudbe - PocetakPosudbe).TotalDays);
            decimal dovoz = 0, najamAuta = 0, najamPrikolice = 0;
            using (var db = new RentacarEntities())
            {
                foreach (var item in db.Lokacije)
                {
                    if (this.Lokacija == item.LokacijaID)
                    {
                        dovoz = item.CijenaDovoza;
                    }
                }
                foreach (var item in db.Vozila)
                {
                    if (this.Vozilo == item.VoziloID)
                    {
                        najamAuta = item.DnevniNajam;
                    }
                }
                if (Prikolica != null)
                {
                    foreach (var item in db.Prikolice)
                    {
                        if (this.Prikolica == item.PrikolicaID)
                        {
                            najamPrikolice = item.DnevniNajam;
                        }
                    }
                }
                return dovoz + brojDana * (najamAuta + najamPrikolice);
            }
        }
    }
}
